"""
Generador de Reportes para OSINT-Nexus
Crea reportes en PDF con los resultados de los análisis OSINT
"""
import os
import json
from datetime import datetime
from typing import Dict, List, Any, Optional
from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT

class ReportGenerator:
    """Generador de reportes PDF para análisis OSINT"""
    
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self.custom_styles = self._create_custom_styles()
        
    def _create_custom_styles(self) -> Dict[str, ParagraphStyle]:
        """Crea estilos personalizados para el reporte"""
        custom_styles = {}
        
        # Título principal
        custom_styles['Title'] = ParagraphStyle(
            'CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            alignment=TA_CENTER,
            textColor=colors.darkblue
        )
        
        # Subtítulos
        custom_styles['Heading2'] = ParagraphStyle(
            'CustomHeading2',
            parent=self.styles['Heading2'],
            fontSize=16,
            spaceAfter=12,
            spaceBefore=20,
            textColor=colors.darkblue
        )
        
        # Subtítulos menores
        custom_styles['Heading3'] = ParagraphStyle(
            'CustomHeading3',
            parent=self.styles['Heading3'],
            fontSize=14,
            spaceAfter=8,
            spaceBefore=12,
            textColor=colors.darkgreen
        )
        
        # Texto normal
        custom_styles['Normal'] = ParagraphStyle(
            'CustomNormal',
            parent=self.styles['Normal'],
            fontSize=10,
            spaceAfter=6
        )
        
        # Texto de código
        custom_styles['Code'] = ParagraphStyle(
            'CustomCode',
            parent=self.styles['Code'],
            fontSize=9,
            fontName='Courier',
            backColor=colors.lightgrey,
            leftIndent=20,
            rightIndent=20
        )
        
        return custom_styles
    
    def generate_report(self, analysis_data: Dict[str, Any], output_path: str = "osint_report.pdf") -> str:
        """Genera un reporte PDF completo con los datos de análisis"""
        try:
            doc = SimpleDocTemplate(output_path, pagesize=A4)
            story = []
            
            # Página de título
            story.extend(self._create_title_page(analysis_data))
            
            # Resumen ejecutivo
            story.extend(self._create_executive_summary(analysis_data))
            
            # Detalles del análisis
            story.extend(self._create_analysis_details(analysis_data))
            
            # Conclusiones y recomendaciones
            story.extend(self._create_conclusions(analysis_data))
            
            # Apéndices
            story.extend(self._create_appendices(analysis_data))
            
            # Construir el documento
            doc.build(story)
            
            return output_path
            
        except Exception as e:
            print(f"Error generando reporte: {str(e)}")
            return ""
    
    def _create_title_page(self, analysis_data: Dict[str, Any]) -> List:
        """Crea la página de título"""
        elements = []
        
        # Título principal
        title = Paragraph("OSINT-Nexus Analysis Report", self.custom_styles['Title'])
        elements.append(title)
        elements.append(Spacer(1, 30))
        
        # Información del análisis
        analysis_info = [
            ["Analysis Type:", analysis_data.get("analysis_type", "Unknown")],
            ["Target:", analysis_data.get("target", "Unknown")],
            ["Date:", datetime.now().strftime("%Y-%m-%d %H:%M:%S")],
            ["Generated by:", "OSINT-Nexus v1.0.0"]
        ]
        
        info_table = Table(analysis_info, colWidths=[2*inch, 4*inch])
        info_table.setStyle(TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 12),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        
        elements.append(info_table)
        elements.append(Spacer(1, 30))
        
        # Advertencia ética
        warning_text = """
        <b>ADVERTENCIA ÉTICA:</b><br/>
        Este reporte contiene información obtenida únicamente de fuentes públicas y legales. 
        El uso de esta información debe cumplir con todas las leyes y regulaciones aplicables. 
        Es responsabilidad del usuario asegurar que el uso de esta información es ético y legal.
        """
        warning = Paragraph(warning_text, self.custom_styles['Normal'])
        elements.append(warning)
        
        return elements
    
    def _create_executive_summary(self, analysis_data: Dict[str, Any]) -> List:
        """Crea el resumen ejecutivo"""
        elements = []
        
        # Título de sección
        title = Paragraph("Executive Summary", self.custom_styles['Heading2'])
        elements.append(title)
        
        # Resumen general
        summary_text = f"""
        This report presents the results of an OSINT (Open Source Intelligence) analysis 
        conducted on <b>{analysis_data.get('target', 'Unknown')}</b>. The analysis was performed 
        using multiple specialized tools and techniques to gather publicly available information.
        """
        summary = Paragraph(summary_text, self.custom_styles['Normal'])
        elements.append(summary)
        elements.append(Spacer(1, 12))
        
        # Estadísticas clave
        stats = analysis_data.get("statistics", {})
        if stats:
            stats_text = f"""
            <b>Key Findings:</b><br/>
            • Total data points discovered: {stats.get('total_findings', 0)}<br/>
            • Analysis duration: {stats.get('scan_duration', 'Unknown')} seconds<br/>
            • Tools utilized: {', '.join(stats.get('tools_used', []))}<br/>
            • Errors encountered: {stats.get('errors', 0)}
            """
            stats_para = Paragraph(stats_text, self.custom_styles['Normal'])
            elements.append(stats_para)
        
        return elements
    
    def _create_analysis_details(self, analysis_data: Dict[str, Any]) -> List:
        """Crea los detalles del análisis"""
        elements = []
        
        # Título de sección
        title = Paragraph("Analysis Details", self.custom_styles['Heading2'])
        elements.append(title)
        
        # Detalles específicos según el tipo de análisis
        analysis_type = analysis_data.get("analysis_type", "")
        
        if analysis_type == "domain":
            elements.extend(self._create_domain_analysis_details(analysis_data))
        elif analysis_type == "email":
            elements.extend(self._create_email_analysis_details(analysis_data))
        elif analysis_type == "username":
            elements.extend(self._create_username_analysis_details(analysis_data))
        elif analysis_type == "social":
            elements.extend(self._create_social_analysis_details(analysis_data))
        
        return elements
    
    def _create_domain_analysis_details(self, analysis_data: Dict[str, Any]) -> List:
        """Crea detalles específicos para análisis de dominio"""
        elements = []
        
        # Información del dominio
        domain_info = analysis_data.get("domain_info", {})
        if domain_info:
            subtitle = Paragraph("Domain Information", self.custom_styles['Heading3'])
            elements.append(subtitle)
            
            domain_table_data = [
                ["Domain", domain_info.get("domain", "N/A")],
                ["Registrar", domain_info.get("registrar", "N/A")],
                ["Creation Date", str(domain_info.get("creation_date", "N/A"))],
                ["Expiration Date", str(domain_info.get("expiration_date", "N/A"))]
            ]
            
            domain_table = Table(domain_table_data, colWidths=[2*inch, 4*inch])
            domain_table.setStyle(TableStyle([
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                ('GRID', (0, 0), (-1, -1), 1, colors.grey)
            ]))
            elements.append(domain_table)
            elements.append(Spacer(1, 12))
        
        # Subdominios
        subdomains = analysis_data.get("subdomains", [])
        if subdomains:
            subtitle = Paragraph("Subdomains Discovered", self.custom_styles['Heading3'])
            elements.append(subtitle)
            
            subdomain_data = [["Subdomain", "IP Address", "Source"]]
            for subdomain in subdomains[:10]:  # Limitar a 10 para el reporte
                subdomain_data.append([
                    subdomain.get("name", "N/A"),
                    subdomain.get("ip", "N/A"),
                    subdomain.get("source", "N/A")
                ])
            
            subdomain_table = Table(subdomain_data, colWidths=[2.5*inch, 2*inch, 1.5*inch])
            subdomain_table.setStyle(TableStyle([
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                ('GRID', (0, 0), (-1, -1), 1, colors.grey),
                ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey)
            ]))
            elements.append(subdomain_table)
            elements.append(Spacer(1, 12))
        
        # Tecnologías
        technologies = analysis_data.get("technologies", [])
        if technologies:
            subtitle = Paragraph("Technologies Detected", self.custom_styles['Heading3'])
            elements.append(subtitle)
            
            tech_data = [["Technology", "Version", "Source"]]
            for tech in technologies[:10]:  # Limitar a 10
                tech_data.append([
                    tech.get("name", "N/A"),
                    tech.get("version", "N/A"),
                    tech.get("source", "N/A")
                ])
            
            tech_table = Table(tech_data, colWidths=[2.5*inch, 2*inch, 1.5*inch])
            tech_table.setStyle(TableStyle([
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                ('GRID', (0, 0), (-1, -1), 1, colors.grey),
                ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey)
            ]))
            elements.append(tech_table)
        
        return elements
    
    def _create_email_analysis_details(self, analysis_data: Dict[str, Any]) -> List:
        """Crea detalles específicos para análisis de email"""
        elements = []
        
        # Información del email
        email_info = analysis_data.get("email_info", {})
        if email_info:
            subtitle = Paragraph("Email Information", self.custom_styles['Heading3'])
            elements.append(subtitle)
            
            email_table_data = [
                ["Email Address", email_info.get("email", "N/A")],
                ["Username", email_info.get("username", "N/A")],
                ["Domain", email_info.get("domain", "N/A")],
                ["Exists", str(email_info.get("exists", "N/A"))],
                ["Disposable", str(email_info.get("disposable", "N/A"))],
                ["Webmail", str(email_info.get("webmail", "N/A"))]
            ]
            
            email_table = Table(email_table_data, colWidths=[2*inch, 4*inch])
            email_table.setStyle(TableStyle([
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                ('GRID', (0, 0), (-1, -1), 1, colors.grey)
            ]))
            elements.append(email_table)
            elements.append(Spacer(1, 12))
        
        # Brechas de datos
        breaches = analysis_data.get("breaches", [])
        if breaches:
            subtitle = Paragraph("Data Breaches", self.custom_styles['Heading3'])
            elements.append(subtitle)
            
            breach_data = [["Breach Name", "Date", "Records Affected", "Data Types"]]
            for breach in breaches[:10]:  # Limitar a 10
                breach_data.append([
                    breach.get("name", "N/A"),
                    breach.get("breach_date", "N/A"),
                    str(breach.get("pwn_count", "N/A")),
                    ", ".join(breach.get("data_classes", []))[:50] + "..."
                ])
            
            breach_table = Table(breach_data, colWidths=[2*inch, 1.5*inch, 1.5*inch, 1*inch])
            breach_table.setStyle(TableStyle([
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 8),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                ('GRID', (0, 0), (-1, -1), 1, colors.grey),
                ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey)
            ]))
            elements.append(breach_table)
        
        return elements
    
    def _create_username_analysis_details(self, analysis_data: Dict[str, Any]) -> List:
        """Crea detalles específicos para análisis de username"""
        elements = []
        
        # Información del username
        username = analysis_data.get("username", "Unknown")
        subtitle = Paragraph(f"Username Analysis: {username}", self.custom_styles['Heading3'])
        elements.append(subtitle)
        
        # Perfiles encontrados
        profiles = analysis_data.get("profiles", [])
        if profiles:
            found_profiles = [p for p in profiles if p.get("exists")]
            
            subtitle = Paragraph(f"Social Profiles Found ({len(found_profiles)})", self.custom_styles['Heading3'])
            elements.append(subtitle)
            
            profile_data = [["Platform", "URL", "Status"]]
            for profile in found_profiles[:15]:  # Limitar a 15
                profile_data.append([
                    profile.get("platform", "N/A").title(),
                    profile.get("url", "N/A"),
                    "Found" if profile.get("exists") else "Not Found"
                ])
            
            profile_table = Table(profile_data, colWidths=[1.5*inch, 4*inch, 1*inch])
            profile_table.setStyle(TableStyle([
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                ('GRID', (0, 0), (-1, -1), 1, colors.grey),
                ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey)
            ]))
            elements.append(profile_table)
        
        return elements
    
    def _create_social_analysis_details(self, analysis_data: Dict[str, Any]) -> List:
        """Crea detalles específicos para análisis social"""
        elements = []
        
        # Información del perfil
        profile_info = analysis_data.get("profile_info", {})
        if profile_info:
            subtitle = Paragraph("Profile Information", self.custom_styles['Heading3'])
            elements.append(subtitle)
            
            profile_table_data = [
                ["Platform", profile_info.get("platform", "N/A").title()],
                ["Username", profile_info.get("username", "N/A")],
                ["Display Name", profile_info.get("display_name", "N/A")],
                ["Followers", str(profile_info.get("followers_count", "N/A"))],
                ["Verified", str(profile_info.get("verified", "N/A"))]
            ]
            
            profile_table = Table(profile_table_data, colWidths=[2*inch, 4*inch])
            profile_table.setStyle(TableStyle([
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                ('GRID', (0, 0), (-1, -1), 1, colors.grey)
            ]))
            elements.append(profile_table)
        
        return elements
    
    def _create_conclusions(self, analysis_data: Dict[str, Any]) -> List:
        """Crea las conclusiones y recomendaciones"""
        elements = []
        
        # Título de sección
        title = Paragraph("Conclusions and Recommendations", self.custom_styles['Heading2'])
        elements.append(title)
        
        # Conclusiones generales
        conclusions_text = """
        <b>Key Conclusions:</b><br/>
        • The analysis revealed multiple data points and connections<br/>
        • Public information was successfully gathered from various sources<br/>
        • The target shows presence across multiple platforms and services<br/>
        • Several potential security and privacy implications were identified
        """
        conclusions = Paragraph(conclusions_text, self.custom_styles['Normal'])
        elements.append(conclusions)
        elements.append(Spacer(1, 12))
        
        # Recomendaciones
        recommendations_text = """
        <b>Recommendations:</b><br/>
        • Review and update privacy settings on all discovered platforms<br/>
        • Consider implementing additional security measures<br/>
        • Monitor for any suspicious activity or unauthorized access<br/>
        • Regularly audit and clean up online presence<br/>
        • Consider using a password manager and enabling two-factor authentication
        """
        recommendations = Paragraph(recommendations_text, self.custom_styles['Normal'])
        elements.append(recommendations)
        
        return elements
    
    def _create_appendices(self, analysis_data: Dict[str, Any]) -> List:
        """Crea los apéndices del reporte"""
        elements = []
        
        # Título de sección
        title = Paragraph("Appendices", self.custom_styles['Heading2'])
        elements.append(title)
        
        # Apéndice A: Metadatos del análisis
        subtitle = Paragraph("Appendix A: Analysis Metadata", self.custom_styles['Heading3'])
        elements.append(subtitle)
        
        metadata = analysis_data.get("metadata", {})
        if metadata:
            meta_text = f"""
            <b>Analysis Details:</b><br/>
            • Scan Duration: {metadata.get('scan_time', 'N/A')} seconds<br/>
            • Tools Used: {', '.join(metadata.get('tools_used', []))}<br/>
            • Errors Encountered: {len(metadata.get('errors', []))}<br/>
            • Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
            """
            meta_para = Paragraph(meta_text, self.custom_styles['Normal'])
            elements.append(meta_para)
        
        # Apéndice B: Datos técnicos
        subtitle = Paragraph("Appendix B: Technical Data", self.custom_styles['Heading3'])
        elements.append(subtitle)
        
        tech_text = """
        <b>Technical Information:</b><br/>
        • Report generated by OSINT-Nexus v1.0.0<br/>
        • All data collected from public sources only<br/>
        • No unauthorized access or hacking techniques used<br/>
        • Analysis conducted in compliance with ethical guidelines
        """
        tech_para = Paragraph(tech_text, self.custom_styles['Normal'])
        elements.append(tech_para)
        
        return elements